### ISSUE TITLE
Issue with playback buttons

### ISSUE THREAD

**Issue by bruno-brant** [gmusic-utils/ytmusic.js#24]
It seems YT Music changed some CSS styles that are being used by ytmusic.js to select the playback ("media") buttons, as can be seem from my post at [GPMDP issues.](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3920#issuecomment-790641150) 

I did just some preliminary testing, but it seems that what happened was simple: YT dropped the `left-controls` and `right-controls` classes from the buttons. The fix is simple enough, but I'd like to see if repo contributors can confirm that this was the change, since I have no background on this lib and am only superficially analyzing the issue.

**Comment by jostrander** [comment]
![image](https://user-images.githubusercontent.com/760989/109976202-806f9880-7cc9-11eb-9440-c4441e90dd58.png)
I'm still seeing these classes present, however, I may not be selected to receive the new web version yet, as Google usually does staged rollouts of changes.

**Comment by bruno-brant** [comment]
Hmm, it seems I made a stupid mistake, I inverted the classes in the query. The classes are there. I'm not sure why it wouldn't be working.

**Comment by jostrander** [comment]
Fixed in 86f4a430fac5e4ecf357c2719858b33d760c524b, closing. GPMDP will need to pull this change in.
